export interface Doc {
  kind: "md" | "ana" | "yaml";
  file: string;
  title: string;
  body: string;
}

export const DOCS: Record<string, Doc> = {
  "vault-index": {
    kind: "md",
    file: "vault-index.md",
    title: "Vault index",
    body: `# Vault index

Root map of the **autonomous-agent** vault (workspace agent V0). This document is generated by \`graph-walker\` and reviewed by the \`curator\` agent.

> **Status 05 Sep 2026:** 246 nodes · 512 edges · 4 updates today · 3 open [NEEDS-*] flags.

## Vault structure

| Area | Contents | Active notes |
| --- | --- | --- |
| \`cryptography\` | primitives & schemes | 21 |
| \`foundations\` | consensus & base-layer mechanisms | 42 |
| \`platforms\` | L1/L2, rollups, infrastructure | 80 |
| \`applications\` | DeFi, NFT, DAO | 47 |
| \`market\` | market behaviour & signals | 35 |
| \`cross-cutting\` | MEV, security, agents | 21 |

## Recently highlighted notes

- [[MEV]] — enriched 05 Sep 2026 (largest hub, degree 15)
- [[Memecoin]] — created 05 Sep 2026 from the knowledge inbox
- [[Bonding Curve]] — created 05 Sep 2026 from the knowledge inbox
- [[Copy Trading]] — NEEDS-CLASSIFICATION flag (06:00 scan)

## Writing rules

1. One concept per note; title in \`Title Case\`.
2. Reference other concepts with the wikilink \`[[Title]]\`.
3. If a note stays below degree 2 for 30 days, \`graph-walker\` proposes a relink or an archive.`,
  },
  "graph-walk": {
    kind: "md",
    file: "graph-walk.md",
    title: "Graph walk — procedure",
    body: `# Graph walk — procedure

SOP document for the \`graph-walker\` cron job (every 6h, last run 12:00).

## Goal

Keep the graph tidy: no orphan notes, no duplicate notes, and every node with at least one meaningful edge.

## Steps

1. **Collect every node** whose \`updated\` is older than 14 days.
2. **Compute the degree** of each node; mark problem candidates:
   - degree 0 → *orphan*
   - degree 1 and not referenced by any other note → *pendant*
   - more than 20 incoming edges from a single layer → *hub* candidate
3. **Propose relinks**: match the title against the text of other notes via similarity search, capped at 5 proposals per walk.
4. **Write a report** to the activity log; never modify a note without approval via chat.

## Threshold rules

| Condition | Action |
| --- | --- |
| degree 0 for 30 days | propose archive |
| degree 1 for 30 days | propose relink |
| [[NEEDS-*]] unanswered for 7 days | propose re-flag |

## Configuration

- Frequency: \`every 6h\`
- Node budget per walk: 18
- Mode: **review-only** (no direct writes)`,
  },
  taxonomy: {
    kind: "md",
    file: "taxonomy.md",
    title: "Taxonomy knowledge graph",
    body: `# Taxonomy knowledge graph

Node labelling scheme. Every node has exactly one **layer** and one **type**.

## Layer

| Layer | Meaning |
| --- | --- |
| \`cryptography\` | cryptographic primitives: signatures, commitments, proofs |
| \`foundations\` | base-layer mechanisms: consensus, mempool, accounts |
| \`platforms\` | L1/L2, rollups, infrastructure & sequencing |
| \`applications\` | DeFi / NFT / DAO products on top of a chain |
| \`market\` | market behaviour: liquidity, tokens, signals |
| \`cross-cutting\` | spans many layers: MEV, agents, governance |

## Type

- \`system\` — system-level mechanism (78)
- \`fundamental\` — base primitive (48)
- \`economy\` — incentive / economic structure (30)
- \`programming\` — implementation detail (26)
- \`concept\` — recurring idea (26)
- \`cross-cutting\` — across layers (19)
- \`trading\` — market-side pattern (10)
- \`blockchain\` — chain-level plumbing (9)

## Classification rules

- A mechanism used by many layers → \`cross-cutting\`, not owned by any single layer.
- \`market\` notes are observations, not specifications — update them when conditions change.
- Default layer for new notes from the inbox: \`applications\` or \`foundations\`, unless shown otherwise.`,
  },
  mev: {
    kind: "md",
    file: "notes/MEV.md",
    title: "MEV",
    body: `# MEV

**Maximal extractable value** — value a block builder/proposer can extract by reordering, inserting, or censoring transactions inside a block. Hub node: **degree 15**, layer \`cross-cutting\`.

## Summary

MEV comes from an *ordering* gap: whoever holds the right to order transactions can capture the price difference ahead of other users.

## Extraction patterns

- [[Sandwich Attack]] — wrap the victim's order with a buy/sell on both sides
- **Frontrunning** — get in ahead of a public transaction
- **Backrunning** — execute right after the transaction that creates the opportunity

## Key connections

- [[MEV-Boost Relay]] — builder-proposer market via a relay
- [[Proposer-Builder Separation]] — splits the builder and proposer roles
- [[Private Mempool]] — a direct channel to avoid frontrunning

## Latest agent note

> Enriched 05 Sep 2026, 11:00 — connected new edges to the *applications* layer after an inbox input. No open flags.`,
  },
  "bonding-curve": {
    kind: "md",
    file: "notes/Bonding Curve.md",
    title: "Bonding Curve",
    body: `# Bonding Curve

A continuous token-pricing mechanism: price is a function of \`supply\`, so the first purchase is cheap and each later purchase costs more. Created from the knowledge inbox **05 Sep 2026, 06:30**.

## General formula

\`price(S) = a · Sᵏ\` — as supply rises, price follows the curve upward.

## Common variants

- **Linear** — price rises in proportion to supply
- **Power** — \`k > 1\`, a steeper acceleration (common for *token launches*)
- **Logarithmic** — growth flattens, stable at high prices

## Why it is used

1. Continuous liquidity from the first block (no orderbook needed)
2. Transparent, deterministic pricing
3. A common mechanism in [[Liquidity Bootstrapping Pool]], [[Fair Launch Mechanism]], and \`market\` token launches

## Agent note

> Connected to 4 new nodes today. The \`curator\` agent verified the formula against curated sources; no conflicts.`,
  },
  memecoin: {
    kind: "md",
    file: "notes/Memecoin.md",
    title: "Memecoin",
    body: `# Memecoin

A token whose value is driven by attention, narrative, and community — not by cash flow. Created from the knowledge inbox **05 Sep 2026, 09:00**.

## Defining traits

- Supply is often capped (burn) or made scarce by design
- Price is highly sensitive to narrative & virality
- Short life cycle: launch → FOMO → peak → rotation

## Patterns observed in the graph

- Launches usually go through [[Bonding Curve]] or [[Liquidity Bootstrapping Pool]]
- Many are grouped as \`market\` because their behaviour is observational
- Rotation signals: funding rate, volume, narrative dominance (see the 04 Sep analysis)

## Agent note

> Created 05 Sep 2026 from an inbox input (source: daily curation). Status active, no flags yet.`,
  },
  "agent-readme": {
    kind: "md",
    file: "agent-readme.md",
    title: "Agent README",
    body: `# Agent README

The local agents that maintain this vault. Read this before asking the chat.

## Who the agents are

- **curator** — maintains the knowledge graph: sync, classification, verification (active)
- **researcher** — scans curated sources & the inbox, proposes new nodes (busy)
- **indexer** — turns the projects inbox into notes (idle)

## What the agents do automatically

| Job | When | Effect |
| --- | --- | --- |
| \`process-inbox-knowledge\` | every 30 min | input → new node/edge |
| \`process-inbox-projects\` | every 30 min | project → \`programming\` note |
| \`graph-walker\` | every 6h | topology audit, relink proposals |
| \`scan-curated-sources\` | daily 06:00 | compare sources, flag anomalies |

## How to interact

- Type a question in **Agent chat** (right panel).
- Wikilinks \`[[Title]]\` in an answer are clickable and highlight the node in the graph.
- Plain-text prompts, no special syntax: *"why is MEV up?"* — the agent answers from notes + analyses.`,
  },
  "agent-manifest": {
    kind: "yaml",
    file: "agent-manifest.yaml",
    title: "agent-manifest.yaml",
    body: `\`\`\`yaml
# autonomous-agent V0 agent manifest
name: autonomous-agent
version: 0.1.0
model: kimi-k3
mode: autonomous

agents:
  curator:
    role: graph-maintainer
    caps: [classify, verify, relink]
  researcher:
    role: source-scanner
    caps: [scan, propose]
  indexer:
    role: inbox-processor
    caps: [ingest, create-note]

pipeline:
  process-inbox-knowledge: { every: 30m }
  process-inbox-projects:  { every: 30m }
  graph-walker:            { every: 6h, mode: review-only }
  scan-curated-sources:    { every: daily-0600 }

graph:
  node-count: 246
  edge-count: 512
  review-threshold: review-only
\`\`\``,
  },
  "ana-graph-health": {
    kind: "ana",
    file: "analysis/graph-health-05-sep.md",
    title: "Graph health — audit 05 Sep",
    body: `# Graph health — audit 05 Sep

Full topology audit, run by the **curator** agent on 05 Sep 2026 13:30 (12 min).

<div class="ana-kv"><div class="kv"><span class="k">nodes</span><span class="v">246</span></div><div class="kv"><span class="k">edges</span><span class="v">512</span></div><div class="kv"><span class="k">hubs (degree ≥ 12)</span><span class="v">3</span></div><div class="kv"><span class="k">orphans</span><span class="v">0</span></div></div>

## Edge distribution per layer

<div class="barchart"><div class="bc-row"><span class="bc-k">platforms</span><div class="bc-track"><div class="bc-fill" style="width:100%"></div></div><span class="bc-v">182</span></div><div class="bc-row"><span class="bc-k">applications</span><div class="bc-track"><div class="bc-fill" style="width:86%"></div></div><span class="bc-v">157</span></div><div class="bc-row"><span class="bc-k">foundations</span><div class="bc-track"><div class="bc-fill" style="width:61%"></div></div><span class="bc-v">111</span></div><div class="bc-row"><span class="bc-k">market</span><div class="bc-track"><div class="bc-fill" style="width:44%"></div></div><span class="bc-v">80</span></div><div class="bc-row"><span class="bc-k">cryptography</span><div class="bc-track"><div class="bc-fill" style="width:27%"></div></div><span class="bc-v">49</span></div><div class="bc-row"><span class="bc-k">cross-cutting</span><div class="bc-track"><div class="bc-fill" style="width:25%"></div></div><span class="bc-v">46</span></div></div>

## Key findings

1. **No orphans.** All 246 nodes have degree ≥ 1 — the result of last week's relink batch.
2. **Three stable hubs:** [[MEV]] (15), [[EIP-1559 Fee Market]] (14), [[Proposer-Builder Separation]] (12).
3. **[[Copy Trading]]** is the only market node with an open flag — not yet classified into the right market pattern.
4. Cross-layer density is up 4% since the previous audit; most of the increase comes from applications ↔ market edges.

## Recommendations

- Verify the classification of [[Copy Trading]] (flagged since 06:00).
- Watch \`applications\` growth — above 170 edges, consider a new sub-layer.
- Next audit scheduled: 06 Sep 2026, 13:30.`,
  },
  "ana-orphans": {
    kind: "ana",
    file: "analysis/orphans-hubs-05-sep.md",
    title: "Orphan notes & new hubs",
    body: `# Orphan notes & new hubs

Long-range topology analysis by **graph-walker**, 05 Sep 2026 11:00 (8 min).

## Before vs after the walk

| Metric | Before | After |
| --- | --- | --- |
| orphans (degree 0) | 2 | 0 |
| pendants (degree 1) | 9 | 6 |
| hubs (degree ≥ 12) | 2 | 3 |
| new edges | — | 14 |

## What the walker did

- Connected 2 orphans to their parent layer: one to \`foundations\`, one to \`applications\`.
- Proposed 5 relinks; **2 accepted** by the curator agent, 3 rejected for weak similarity.
- Promoted [[MEV]] to a hub: +3 edges from \`market\` notes that mention value extraction.

## Note

The remaining pendants (6) are all \`programming\` notes younger than 30 days — expected, not yet referenced. The next walk checks again.`,
  },
  "ana-mempool": {
    kind: "ana",
    file: "analysis/mempool-application-density.md",
    title: "Mempool density → application layer",
    body: `# Mempool density → application layer

Correlation analysis by **researcher**, 04 Sep 2026 22:10 (15 min). Data: 30 days of graph logs.

## Question

Does a rise in mempool activity (queue depth, fee spikes) precede new nodes being added to the application layer?

## Findings

<div class="barchart"><div class="bc-row"><span class="bc-k">Mempool × applications</span><div class="bc-track"><div class="bc-fill" style="width:78%"></div></div><span class="bc-v">+0.78</span></div><div class="bc-row"><span class="bc-k">Mempool × market</span><div class="bc-track"><div class="bc-fill" style="width:44%"></div></div><span class="bc-v">+0.44</span></div><div class="bc-row"><span class="bc-k">Mempool × cryptography</span><div class="bc-track"><div class="bc-fill" style="width:19%"></div></div><span class="bc-v">+0.19</span></div></div>

- Correlation **0.78** between a mempool *fee spike* and application-node creation 3–5 days later.
- Consistent pattern: when [[EIP-1559 Fee Market]] heats up, the knowledge inbox carries more DeFi material.
- Correlation with other layers is weak — the effect is specific to applications, not the whole vault.

## Recommendations

- Raise \`process-inbox-knowledge\` frequency to every 15 min when a fee spike exceeds 2σ (already proposed to the config).
- Use this signal to prioritise curation of application sources the next day.`,
  },
  "ana-agent": {
    kind: "ana",
    file: "analysis/agent-behavior-30d.md",
    title: "Agent behaviour summary (30 days)",
    body: `# Agent behaviour summary — 30 days

Self-audit of agent behaviour by **curator**, 03 Sep 2026 18:00 (4 min).

## Work volume

| Job | Runs | Real updates | Idle |
| --- | --- | --- | --- |
| process-inbox-knowledge | 1440 | 38 | 1402 |
| process-inbox-projects | 1440 | 11 | 1429 |
| graph-walker | 120 | 9 | 111 |
| scan-curated-sources | 30 | 7 | 23 |

## Quality

- **Relink acceptance rate** (proposed → approved): 68% — above the 50% threshold.
- **False-positive \`NEEDS-*\` flags**: 2 of 7 (29%) — down from 41% last month.
- **Idle time** high (97% of runs) — normal for a wake-gate: the agent only works when there is new input.

## Reflection

1. \`process-inbox-projects\` rarely produces updates — check whether its wake-gate is too strict.
2. One false positive came from a curated source that turned out to be a duplicate — adding dedup is advised.
3. No behaviour changes needed for \`graph-walker\`; the topology audit is healthy.`,
  },
};
